language: ruby
os: linux
dist: xenial

cache:
  - bundler

rvm:
  - 2.5
  - 2.6
  - 2.7
  - 3.0

env:
  global:
    - CC_TEST_REPORTER_ID=d1d9c0636042863489880dbdf1c8865721b9b70f4199d612d77ee2dcfc803704

before_install:
  - gem update --system
  - gem install bundler

before_script:
  - bundle update
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bin/rake

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
